#Requires -Version 5.1
<#
.SYNOPSIS
  Generate a third-party dependency notice list from cargo metadata.

.DESCRIPTION
  Writes docs/THIRD_PARTY_LICENSES.md with direct and transitive crate names,
  versions, and license fields reported by crates.io metadata.
  Run before release packaging so the notices match the lockfile.
#>
param(
    [string]$OutPath = 'docs/THIRD_PARTY_LICENSES.md'
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
Push-Location $repoRoot
try {
    # cargo may write progress to stderr; do not treat that as a terminating error.
    $prevEap = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    $metaLines = & cargo metadata --format-version 1 --locked 2>$null
    $metaCode = $LASTEXITCODE
    $ErrorActionPreference = $prevEap
    if ($metaCode -ne 0) { throw "cargo metadata failed: $metaCode" }
    $jsonText = if ($metaLines -is [array]) { $metaLines -join "`n" } else { [string]$metaLines }
    $meta = $jsonText | ConvertFrom-Json
    $workspaceIds = @($meta.workspace_members)
    $packages = @($meta.packages | Where-Object { $workspaceIds -notcontains $_.id -and $_.source })

    $rows = foreach ($p in ($packages | Sort-Object name, version -Unique)) {
        $license = if ($p.license) { [string]$p.license } else { 'UNKNOWN' }
        $repo = if ($p.repository) { [string]$p.repository } else { '' }
        [pscustomobject]@{
            name     = $p.name
            version  = $p.version
            license  = $license
            repo     = $repo
        }
    }

    $lockPath = Join-Path $repoRoot 'Cargo.lock'
    $lockSha = if (Test-Path -LiteralPath $lockPath) {
        (Get-FileHash -LiteralPath $lockPath -Algorithm SHA256).Hash.ToLowerInvariant().Substring(0, 16)
    } else {
        'unknown'
    }
    $lines = @(
        '# Third-party licenses'
        ''
        "Lockfile: Cargo.lock (sha256-prefix ``$lockSha``; workspace crates excluded)."
        ''
        'MPGS itself is not dual-licensed by this file. This notice lists Rust crate dependencies of the server/dbtool workspace as reported by `cargo metadata`.'
        'Desktop (Tauri) and npm dependencies are listed in the Desktop / Web section below as package names only; run the frontend license tooling before a signed store release if a full SPDX bundle is required.'
        ''
        '## Rust crates'
        ''
        '| Crate | Version | License |'
        '| --- | --- | --- |'
    )
    foreach ($r in $rows) {
        $lines += ("| {0} | {1} | {2} |" -f $r.name, $r.version, ($r.license -replace '\|', '/'))
    }

    $webPkg = Join-Path $repoRoot 'web\package.json'
    $rootPkg = Join-Path $repoRoot 'package.json'
    $lines += ''
    $lines += '## Desktop / Web npm packages (direct)'
    $lines += ''
    $lines += '| Package | Version | Manifest |'
    $lines += '| --- | --- | --- |'
    foreach ($manifest in @($rootPkg, $webPkg)) {
        if (-not (Test-Path -LiteralPath $manifest)) { continue }
        $pkg = Get-Content -LiteralPath $manifest -Raw | ConvertFrom-Json
        $label = Split-Path $manifest -Leaf
        foreach ($section in @('dependencies', 'devDependencies')) {
            $prop = $pkg.PSObject.Properties[$section]
            if ($null -eq $prop -or $null -eq $prop.Value) { continue }
            $bag = $prop.Value
            foreach ($name in ($bag.PSObject.Properties.Name | Sort-Object)) {
                $lines += ("| {0} | {1} | {2} ({3}) |" -f $name, $bag.$name, $label, $section)
            }
        }
    }

    $lines += ''
    $lines += '## Notes'
    $lines += ''
    $lines += '- Do not treat UNKNOWN license rows as cleared for distribution; resolve them before a public store release.'
    $lines += '- Steam trademarks and brand assets are covered in [STEAM_BRAND_REVIEW.md](STEAM_BRAND_REVIEW.md), not by crate licenses.'
    $lines += '- Regenerated by `scripts/generate_third_party_licenses.ps1`.'

    $out = if ([System.IO.Path]::IsPathRooted($OutPath)) { $OutPath } else { Join-Path $repoRoot $OutPath }
    [System.IO.File]::WriteAllLines($out, $lines)
    Write-Host "Wrote $out ($($rows.Count) crates)"
}
finally {
    Pop-Location
}
